version: '3'
services:
  frontend:
    image: wirthandras/radi-demo-frontend
    env_file:
    - ./environment
    restart: always
    depends_on:
    - backend
    ports:
      - "40050:80"
  backend:
    image: wirthandras/radi-demo-backend
    env_file:
    - ./environment
    restart: always
    depends_on:
    - database
  database:
    image: postgres:15-alpine
    env_file:
    - ./environment
    restart: always
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
    - database
    ports:
      - "40051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: example@email.com
      PGADMIN_DEFAULT_PASSWORD: example_password