version: '3'
services:
  frontend:
    image: wirthandras/radi-demo-frontend:master
    restart: always
    depends_on:
    - backend
    ports:
      - "40050:80"
  backend:
    image: wirthandras/radi-demo-backend:master
    restart: always
    depends_on:
    - database
    ports:
      - "40052:80"
    environment:
      ConnectionStrings__SampleDbConnection: "User ID =useroverrideit;Password=overrideit;Host=database;Port=5432;Database=radidb; Integrated Security=true;Pooling=true;"
  database:
    image: postgres:15-alpine
    environment:
        POSTGRES_PASSWORD: overrideit
        POSTGRES_USER: useroverrideit
        POSTGRES_DATABASE: radidb
        POSTGRES_HOST: database
        POSTGRES_PORT: 5432
    restart: always
    ports:
      - "40053:5432"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
    - database
    ports:
      - "40051:80"
    environment:
        PGADMIN_DEFAULT_EMAIL: test@test.com
        PGADMIN_DEFAULT_PASSWORD: admin